# -*- coding: utf-8 -*-
"""Bay BOT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ln0OHpRV-Ad7Cgl-Puudwx0ssLQ8nipN
"""

!pip install chatterbot_corpus

# লাইব্রেরি ইমপোর্ট
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

# চ্যাটবট তৈরি
chatbot = ChatBot(
    'CustomerSupportBot',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    logic_adapters=[
        'chatterbot.logic.BestMatch',
        'chatterbot.logic.MathematicalEvaluation'
    ],
    database_uri='sqlite:///database.db'
)

# ট্রেনার তৈরি
trainer = ChatterBotCorpusTrainer(chatbot)

# ইংরেজি কপোরাস দিয়ে চ্যাটবট ট্রেন করা
trainer.train("chatterbot.corpus.english")

print("চ্যাটবট প্রস্তুত!")

# চ্যাটবটের সাথে কথোপকথন
while True:
    try:
        user_input = input("আপনার প্রশ্ন লিখুন (Exit লেখলে চ্যাটবট বন্ধ হবে): ")

        if user_input.lower() == 'exit':
            print("চ্যাটবট বন্ধ করা হচ্ছে...")
            break

        response = chatbot.get_response(user_input)
        print("চ্যাটবট: ", response)

    except (KeyboardInterrupt, EOFError, SystemExit):
        break

"""Today my fast day. ✈"""